### ISSUE TITLE
[Question] Is it stable and production ready? What is supported already?

### ISSUE THREAD

**Issue by naiteon** [trampi/node-libhydrogen-binding#2]
I would like to know what is already implemented and tested and what is missing? I ask that because I've noticed the "work in progress" mentioned in the description.

Thank you!

**Comment by trampi** [comment]
Hi @naiteon,
effectively this binding only supports [secret key encryption](https://github.com/trampi/node-libhydrogen-binding/wiki/Secret-key-encryption)

I had no issues with node-libhydrogen-binding in my toy project yet.

**Comment by naiteon** [comment]
Thank you so much for your response!
